interface PlantInterface {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly id?: string;

    // Plant name
    name: string;

    // Maxiumum height in mm the plant is expected to grow.
    description?: number;

    // Maxiumum height in mm the plant is expected to grow.
    ended_at?: Date;

    // Maxiumum height in mm the plant is expected to grow.
    created_at?: Date;

}

export default PlantInterface;